name: enclave
on:
  push:
    paths:
      - 'enclave/**'
  pull_request:
    paths:
      - 'enclave/**'

jobs:
  make_test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Docker cache
        uses: ./.github/workflows/dockercache
        with:
          dockerdir: enclave/docker
          imagename: kbupd-enclave-builder
      - run: make docker_"check clippy test"
        working-directory: enclave
  make_docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Docker cache
        uses: ./.github/workflows/dockercache
        with:
          dockerdir: enclave/docker
          imagename: kbupd-enclave-builder
