name: service
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  make_all:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/service
        with:
          target: all
  make_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/service
        with:
          target: all-debug test
